services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: loan_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - loan-tracking-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app          # Only for development (hot-reload)
    networks:
      - loan-tracking-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:0000@db:5432/loan_db
    depends_on:
      - db
    networks:
      - loan-tracking-network

networks:
  loan-tracking-network:
    driver: bridge

volumes:
  db_data: